### ISSUE TITLE
考虑添加一个类似小爱课程表那样的桌面小组件吗？

### ISSUE THREAD

**Issue by GlaxyMarco** [YiQiuYes/schedule#3]
![a4ddf9cc53e2e460cfab5cb9eda54b1](https://github.com/user-attachments/assets/0f454e5b-023a-4ac6-8a50-1a4a128072ba)
像这样

**Comment by YiQiuYes** [comment]
周末我学下compose，尝试写个试试

**Comment by YiQiuYes** [comment]
已完成小部件开发，请下载最新版
