### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by KirariSpark** [YiQiuYes/schedule#4]
rt，账号密码都对，但是不能登录
![4fa4eb2b9e9da37c5ad71a8d737ae89f](https://github.com/user-attachments/assets/5a1f47e1-db9d-4662-8bcb-79caf0b7fec2)

**Comment by YiQiuYes** [comment]
已经修复，请看最新[release](https://github.com/YiQiuYes/schedule/releases/tag/v0.3.2)
