### ISSUE TITLE
建议将实验课表与课程课表的颜色区分开

### ISSUE THREAD

**Issue by GlaxyMarco** [YiQiuYes/schedule#5]
有用户不知道为什么教务系统的首页课表与APP显示的课表不一致，后查看发现APP课表写了实验课，教务系统首页并没有显示实验课程，建议将两种课程显示颜色区分开。

**Comment by YiQiuYes** [comment]
事实上他们都属于课程，都是同一级别的，分颜色会显突兀

**Comment by YiQiuYes** [comment]
> 有用户不知道为什么教务系统的首页课表与APP显示的课表不一致，后查看发现APP课表写了实验课，教务系统首页并没有显示实验课程，建议将两种课程显示颜色区分开。

事实上他们都属于课程，都是同一级别的，分颜色会显突兀
