### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by KirariSpark** [YiQiuYes/schedule#6]
rt，教务系统网站可以登录，但app登不上
![Screenshot_2024-11-15-14-01-21-676_com microsoft emmx-edit](https://github.com/user-attachments/assets/5beb572f-ce41-4ee5-9db0-85760272dc71)
![IMG_20241115_140336](https://github.com/user-attachments/assets/2d478eaa-f593-4727-97bd-75cb04e4fd0e)

**Comment by YiQiuYes** [comment]
Fix soon

**Comment by YiQiuYes** [comment]
has been fixed [v0.3.9](https://github.com/YiQiuYes/schedule/releases/tag/v0.3.9)
